### ISSUE TITLE
Wrong updated/created date for sensu-influxdb-handler versions

### ISSUE THREAD

**Issue by ccressent** [sensu/bonsai#107]
When switching between `sensu-influxdb-handler` versions on the [bonsai page](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler), the "updated" and "created on" dates on the right do not seem to change; it looks like they stay the same as the latest release. See [3.1.1](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler/versions/3.1.1) vs [3.1.2](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler/versions/3.1.2). All the dates are "February 25, 2019".

For comparison [the pagerduty handler's page](https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler) seems to work fine in that regard.

**Comment by mbiang** [comment]
Thanks @ccressent - we'll take a look.   CC @pzupan

**Comment by pzupan** [comment]
All of the versions for `sensu-influxdb-handler` have a created and updated date of Feb. 25, so it appears the view is working properly.

**Comment by ccressent** [comment]
@pzupan can you clarify what those dates are or where they are coming from then? They don't seem to correspond to anything related to the git/github/release activities, be it for `sensu-influxdb-handler` or `sensu-pagerduty-handler`.

**Comment by pzupan** [comment]
It sounds like those dates are generated at the time the asset is added to bonsai, which is the native behavior of rails.  Is this limited to Enterprise hosted assets?  Perhaps the file importn(as opposed to the github import) is not capturing a relevant date.

**Comment by ccressent** [comment]
I'm not sure what the original intent was with those 2 dates on the right hand side, but here are a few notes as a (new) Bonsai user:

- Created on can either be:
  1. the date when the asset page was created on Bonsai
  2. the date when that particular version was released on github
  3. the date when that particular release was added to Bonsai
That should be the same as ii. anyway.

- Updated can either be:
  1. the date when the asset page was updated on Bonsai
  2. the date when that particular version was updated on github
That shouldn't happen since we would just make a new release, bumping the patch version up.
  3. the date when that particular version was updated on Bonsai
That should be the same as ii. anyway.

Right now I don't know which combination of the above is being used because not all the pages appear to be working the same way: take [sensu-influxdb-handler](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler) and [sensu-pagerduty-handler](https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler); the former keeps the same "updated" date across all the versions one picks while the later changes the "updated" date depending on the version one picks.

Also, even if the dates change like on the page for `sensu-pagerduty-handler`, last time I checked those dates did not necessarily correspond to anything in git/github anyway.

**Comment by pzupan** [comment]
@ccressent I think you are correct.  The only comment I can add is that Bonsai is changing the updated date anytime the asset is re-compiled, so that is why you're seeing some assets with an updated date different than the created date (note I have not confirmed this, but this is the standard configuration in rails).

**Comment by calebhailey** [comment]
It's unclear if this has been resolved, however we should revisit what metadata is even displayed on the asset pages and address any issues at that time.
