### ISSUE TITLE
Github throttling asset download - preventing asset download to some agents

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#135]
Reported in community chat by Kurt Payne

when using assets with a fleet of agents, github appears to  throttle downloads preventing some agents from retrieving the asset.

There was a fix in sensu-go-agent 5.3.0 should prevent the timeout, I'm trying to get more information to see if he's tested with 5.3.0.

**Comment by mbiang** [comment]
Hi @jspaleta - we are unsure of the specifics involved here.  Let us know if you can get some more info, or we can break out and discuss.

**Comment by calebhailey** [comment]
Resolved a long time ago w/ support for caching assets on S3.
