### ISSUE TITLE
Enhancement: Make it possible to delist repositories without admin action.

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#218]
I could really use an asset management option to either hide or delist an asset from public view for assets I manage.

This wlll need discussion to make sure we don't disrupt users.

Here's the problems I'm trying to solve.

1) I accidentally register the wrong github repository from the pull down list. 

2) personal fork of another asset, which as been deprecated for a period of time.. I would like to officially delist/hide the fork from bonsai and delete the fork from github entirely. 

Concerns:
The download urls for the asset binaries should still work, but the web-ui and api endpoints should go dark.

**Comment by mbiang** [comment]
- We should allow collaborators to delete assets.
- We should send a notification that the asset has been deleted to the asset owner, and the user who added the asset to the index.

**Comment by pzupan** [comment]
Added a notifier that will email owner, collaborators and all followers.

**Comment by jspaleta** [comment]
seems to work, but search is broken on staging right now so I can't fully check to make sure
