### ISSUE TITLE
Enhancement: Can we indicate if upstream asset is available?

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#219]
Can bonsai know if a github repository is a fork of another github repository at repository compile time via the github api?

And if so, can bonsai know if that upstream repository is listed as an asset at compile time via the bonsai api?

If yes to both, can we provide a hint in the web UI to users browsing asset that an upstream asset exists?

**Comment by mbiang** [comment]
https://api.github.com/repos/jspaleta/sensu-plugins-http is an example API request that lists a parent repository.  We can use the parent.full_name property to lookup an upstream asset in our database.

**Comment by jspaleta** [comment]
looks good in staging.

:+1:
