### ISSUE TITLE
Enhancement: make it possible to have repository indexed with bare master branch.

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#220]
Right now bonsai requires a .bonsai.yml in the master branch for release compilation to work.

Is there a way we can remove this requirement so that bonsai only needs .bonsai.yml files in a release?

The benefit here is that it opens up additional git workflows where releases are prepped in dedicated release branches.

Not a huge priority, just wondering if the logic could be refactored so we are only relying on information tied to releases.

**Comment by mbiang** [comment]
- We are going to look into the option of simply removing the "master" release, as it provides no actual functionality in bonsai (there are no binaries attached to it, etc).
- We will add compilation logic to show a error if an asset is added that does not contain at least one release.
