### ISSUE TITLE
Enhancement: Allow admins to select preferred namespace in search results

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#224]
This will need some discussion

Idea:
Running site admin may want to make sure certain namespaces are promoted to top of list.

For example for sensu run public bonsai we may want to configure the site to put "sensu" and/or "sensu-plugins" namespaces at top of returns, as an opinionated preference to help users.

In the future... privately run Bonsai implementation may want to configure different preferred namespaces.

**Comment by mbiang** [comment]
- We should create a method prioritize certain namespaces toward the top of the search results

**Comment by jspaleta** [comment]
can't test search is broken in staging
