### ISSUE TITLE
Styling for Asset Readme's seems off

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai#225]
When reading an asset readme, the styling seems significantly different from the style I see on Github:

<img width="763" alt="Screen Shot 2019-09-20 at 11 51 47 AM" src="https://user-images.githubusercontent.com/898627/65342097-0401fc00-dba0-11e9-9834-c1388dd80a01.png">

For example, the H1 text seems smaller than I'd expect and the preformatted text seems to be bolded. The spacing also seems to be different than what I'd expect. Contrast this with what I see on Github:

<img width="991" alt="Screen Shot 2019-09-20 at 12 14 32 PM" src="https://user-images.githubusercontent.com/898627/65342209-4297b680-dba0-11e9-93bc-cd8581bf0ab9.png">

The Github styling seems much cleaner to me. Can we refactor the styling to more closely match Github?

**Comment by mbiang** [comment]
@pzupan - can we look into styling the code blocks similar to how Github does?

**Comment by jspaleta** [comment]
:+1: 
looks good
