### ISSUE TITLE
Bonsai Staging - Disable Email Notificaitons

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai#230]
Is there a way we can turn off the email notifications for activity in the staging environment?  sensu-plugins upstream maintainers got a deprecation notification from staging..which is noise for sure.

**Comment by mbiang** [comment]
Note:  we want to disable the emails that get sent to repository owners.

**Comment by jspaleta** [comment]
i think this is off, not sure how to test...but this is a non-blocker for production
