### ISSUE TITLE
Update ReadMe with local install instructions

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#238]
Goal: Provide enough instructions to stand up an on-prems bonsai index instance.

We'll need to publicly document:
1. install procedure
2. required local configuration
3. self-hosted asset format

**Comment by mbiang** [comment]
1. Update the full list of environment variables with descriptions
2. Need to list third part dependencies - Github, AWS s3, etc.  Detail why these are dependencies and what part of the app uses them.
3. For production environment setup, let's document exactly how to set this app up on Heroku.  Additionally, let's add an app.json file:  https://devcenter.heroku.com/articles/app-json-schema

**Comment by mbiang** [comment]
@jspaleta The local development instructions are in the "update_readme" branch.

**Comment by jspaleta** [comment]
Okay this is a non blocker for deployment to production as this is a repo issue only.
