### ISSUE TITLE
Anchor links within plugin readme's aren't handled correctly

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai#252]
When clicking on an anchor link, I'm not directed to that section of a plugin's readme. Instead, the page stays the same. For example, click on any of the anchor links in https://bonsai.sensu.io/assets/asachs01/sensu-go-cpu-check and observe the lack of change in navigation.

**Comment by jspaleta** [comment]
Looks good.
I just tested the anchor links at 
https://bonsai-asset-index-staging.herokuapp.com/assets/jspaleta/sensu-plugins-redis/versions/4.0.0-jef.3

Example:
https://bonsai-asset-index-staging.herokuapp.com/assets/jspaleta/sensu-plugins-redis/versions/4.0.0-jef.3#files

takes me to the files section of the readme
