### ISSUE TITLE
Ability to mark an asset as private

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai#253]
If a user or customer goes through the guide to enable a plugin to work with Sensu, the net result is that we end up with one or more assets in a user's namespace on Bonsai. This also ends up muddying the waters around plugin ownership. Take this scenario, for example:

* User finds a plugin that they need, but isn't in bonsai
* User follows guide, which results in them uploading the plugin to bonsai to confirm that the plugin works
* Another user finds the same initial non-Sensu-Go-enabled plugin and follows the guide

Now there are 2 copies of the same plugin in bonsai, plus the existing plugin that's in the sensu-plugins namespace. 

The ideal solution IMO would be to mark an asset as private and include that capability as part of the guide. When the plugin is ready, the user should be able to open a PR against the existing plugin's repo to have their changes brought back into the existing plugin. 

Right now, we're incurring unnecessary technical debt without this feature, as someone will have to go through bonsai, contact these users to have them deprecate their assets, or administratively deprecate them--not ideal either way we cut it. 

cc @jspaleta @nixwiz for further comment.

**Comment by jspaleta** [comment]
Technically I don't understand how private would work  as there is no auth available on the api sensuctl uses that would know one user versus another has access to the repo. 

What maybe possible is a Bonsai web-ui "manage asset" option to hide an asset from the normal bonsai search and let repo collaborators still see it in their profile view.  But this has some trade-offs.  It also makes it much harder for use to figure out where the community activity is and where we can help coordinate/nudge the engaged people so we can get them working together in a common codebase.

I'm not sure i'd want to extend a search hide feature that to a .bonsai.yml feature, as any thing in .bonsai.yml is going to be associated with a specific version. We can potential hide a version using .bonsai.yml, but not the repo listing entirely.

Bonsai does now provide a banner indicated that a repository is a child fork from a parent repo already in the Bonsai Index which is meant to do to things
1) hint to users that there is a more official version
2) encourage

It looks like this banner doesn't fire unless the uber-parent repository is listed in Bonsai. We may want to change the fork banner logic and if the uber-parent isn't an asset have a banner that encourages collaborating with the upstream and getting the uber-parent in bonsai as well..ask nicely for them to help upstream get into bonsai.

**Comment by mbiang** [comment]
In order to accomplish this, we propose:

1. Adding a feature under "Manage asset" to Hide from Directory.
1. Clicking this links should hide the asset from all public directory views and search results.
1. if an asset is hidden, the link should read "Show in Directory"
1. This should be available to admins and asset owners.

**Comment by jspaleta** [comment]
Seems to not be working in staging:
I set a repo to private:
https://bonsai-asset-index-staging.herokuapp.com/assets/jspaleta/sensu-plugins-redisto private

Still showing up in recently updated on main page.. probably needs to be hidden there as well.

Also showing up in searches:
https://bonsai-asset-index-staging.herokuapp.com/assets?utf8=%E2%9C%93&supported_platform_id=&q=redis&platforms%5B%5D=&owner_name=

**Comment by pzupan** [comment]
@jspaleta  I can't see the sensu-plugins-redisto asset  (even as admin).  You should be able to see while logged in, but not when you logout.  And you should see a banner on the asset when you select it indicating it is set to private.

**Comment by pzupan** [comment]
Add icon on search results to indicate it's private.
