### ISSUE TITLE
invalid argument(s) received when attempting to install my asset

### ISSUE THREAD

**Issue by Salamek** [sensu/bonsai#276]
Hello, i created new sensu go asset and installation on my sensu go server fails with
```bash
root@sensu:~# sensuctl asset add Salamek/sensu-go-load-check
no version specified, using latest: 0.0.4
fetching bonsai asset: Salamek/sensu-go-load-check:0.0.4
Error: error putting resource 0 (/api/core/v2/namespaces/default/assets/Salamek%2Fsensu-go-load-check): invalid argument(s) received
```

It looks like sensu-api is refusing to accept my asset due to my uppercase "S" in my github account name... 
https://github.com/sensu/sensu-go/blob/8c519bbd3cbae9bc4ae820d5df4a47104a554a46/api/core/v2/asset.go#L113

What to do now (i'm not renaming my account)

**Comment by mbiang** [comment]
Thanks @Salamek - it looks like Bonsai may not be handling uppercase characters in the Github account name.   We'll look into this, and update this issue when we determine a solution.   No need to rename your account 😉

**Comment by pzupan** [comment]
From Aaron:
IIRC github usernames are case insensitive (e.g. https://github.com/salamek/sensu-go-load-check works). As a quick workaround, maybe Bonsai could make sure to lowercase the username too?

**Comment by pzupan** [comment]
Rather than force all owner_names to lowercase, I have altered the find queries to be case insensitive.  We shouldn't have a problem retaining the format of the lowercase name from github but thought I would leave is open to discuss.

**Comment by mbiang** [comment]
- Comment out Line 3 of .env.example (POSTGRES_PASSWORD)

**Comment by mbiang** [comment]
- Let's group all related ENV variables in .env.example
- Place app specific env variables at the top
- Place all non-required or non necessary variables last, and comment them out.

**Comment by mbiang** [comment]
This is an issue with Sensu Go no handling uppercase namespaces correctly.  We are filing an issue to resolve this, but as a workaround we can resolve this by lowercasing all URLs and asset names and namespaces in the following endpoint:   https://bonsai.sensu.io/api/v1/assets/Salamek/sensu-go-load-check/0.0.4/release_asset_builds.   cc @pzupan

**Comment by Salamek** [comment]
This seems to be fixed by https://github.com/sensu/sensu-go/commit/92ac061f544748f80baf28d3ca5bdb11d71a604b
