### ISSUE TITLE
Deprecate asset zip uploads

### ISSUE THREAD

**Issue by calebhailey** [sensu/bonsai#326]
Bonsai currently supports uploading zip archives of new asset builds – a workflow we wanted to support for private repositories. 

<img width="1622" alt="Screen Shot 2021-09-27 at 9 39 01 AM" src="https://user-images.githubusercontent.com/141373/134950176-cf790b56-ff74-4710-9a19-e88805035d4c.png">

_The "-OR- Upload a ZIP file" workflow should be disabled or removed._

This will now be replaced by #325

**Comment by jspaleta** [comment]
The zip upload interface definitely appears to be gone in staging.
