### ISSUE TITLE
Deprecate Github Webhooks

### ISSUE THREAD

**Issue by calebhailey** [sensu/bonsai#327]
Add a flag to disable GitHub webhooks. Moving forward, asset updates should be managed view the new /build API. 

See #324

**Comment by demillir** [comment]
The class-of-interest is `SetupExtensionWebHooksWorker`

**Comment by jspaleta** [comment]
Confirmed changed in staging disable the creation of a github webhook.

### Here is what worked as expected:
1. Added public repo `jspaleta/sensu-plugins-puppet`  to staging and not staging webhook added to github. Production webhook is there.
2. added private repo `jspaleta/private-asset-test`  to staging and no staging webhook added to github

### Deprecated behavior that probably needs to be documented.
Existing staging asset `jspaleta/sensu-asset-playground` with webhook continues to recompile using the webhook installed in github.  Is there any way we can throw a banner note onto the asset that indicates the webhook is still active and it needs to be manually moved from github?
