### ISSUE TITLE
Make AWS S3 mirroring optional

### ISSUE THREAD

**Issue by calebhailey** [sensu/bonsai#330]
Prepare Bonsai for on-prem deployments where users might not need support for mirroring assets on S3.

**Comment by jspaleta** [comment]
Testing on staging.
### Expected behavior 
newly added asset `jspaleta/sensu-plugins-puppet`  shows github download urls as expected in asset definition

### Unexpected behavior
existing asset  `jspaleta/sensu-asset-playground` after recompile still shows s3 urls in asset definition.
