### ISSUE TITLE
Collaborator check when trying to add new assets doesn't pick up team roles

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai#345]
Recently I've been unable to get permissions to add an asset to bonsai for repositories in the sensu github org space where I have commit rights as a member of the github org team. I've had to start adding myself as an individual collaborator.
This must have been a change in how the github API represents commit writes.

**Comment by jspaleta** [comment]
@demillir 
We have a new asset getting this error right now.  We have an engineer @echlebek with commit access on github repo but bonsai says he's not a collaborator

Here's the repo that won't load into bonsai:
https://github.com/sensu/haproxy-check

**Comment by demillir** [comment]
Here is the error message:
There were some problems submitting the form:

    Github URL must be a valid repo on which you are a collaborator.

**Comment by demillir** [comment]
Currently, the code throws this error message in the `validatate_repo_collaborator` method, which has a very simple test:
```
result = octokit.collaborator?(extension.github_repo, user.github_account.username)
```

We need to extend this method to also ask if the user is a member of any `Team` that has access to the repo, where the access either Write, Maintain, Admin.

**Comment by demillir** [comment]
Some docs: https://docs.github.com/en/rest/reference/collaborators#check-if-a-user-is-a-repository-collaborator
